export type UniMapUpdatedEventDetail = {}
export class UniMapUpdatedEvent extends UniCustomEvent<UniMapUpdatedEventDetail> {
	constructor(type : string, detail : UniMapUpdatedEventDetail) {
		super(type, detail)
	}
}

export type UniMapTapEventDetail = {
	latitude : number | null;
	longitude : number | null;
}


export class UniMapTapEvent extends UniPointerEvent {
	detail ?: UniMapTapEventDetail = null
	constructor(type : string, x : number, y : number, clientX : number, clientY : number, pageX : number, pageY : number, screenX : number, screenY : number) {
		super(type, x, y, clientX, clientY, pageX, pageY, screenX, screenY)
	}
// #ifdef APP-ANDROID
// #ifndef VUE3_VAPOR
	override toJSON() : UTSJSONObject {
		const jsonObject : UTSJSONObject = super.toJSON()
		jsonObject.set("bubbles", this.bubbles)
		jsonObject.set("cancelable", this.cancelable)
		jsonObject.set("x", this.x)
		jsonObject.set("y", this.y)
		jsonObject.set("clientX", this.clientX)
		jsonObject.set("clientY", this.clientY)
		jsonObject.set("pageX", this.pageX)
		jsonObject.set("pageY", this.pageY)
		jsonObject.set("screenX", this.screenX)
		jsonObject.set("screenY", this.screenY)
		return jsonObject
	}
// #endif
// #endif
}

export type UniMapRegionChangeEventDetail = {
	skew : number | null;
	rotate : number | null;
}
export class UniMapRegionChangeEvent extends UniCustomEvent<UniMapRegionChangeEventDetail | null> {
	causedBy ?: string | null = null;
	constructor(type : string, detail : UniMapRegionChangeEventDetail | null) {
		super(type, detail)
	}
}

export type UniMapMarkerTapEventDetail = {
	markerId : number | null;
}
export class UniMapMarkerTapEvent extends UniPointerEvent {

	detail ?: UniMapMarkerTapEventDetail = null
	constructor(type : string, x : number, y : number, clientX : number, clientY : number, pageX : number, pageY : number, screenX : number, screenY : number) {
		super(type, x, y, clientX, clientY, pageX, pageY, screenX, screenY)
	}
// #ifdef APP-ANDROID
// #ifndef VUE3_VAPOR
	override toJSON() : UTSJSONObject {
		const jsonObject : UTSJSONObject = super.toJSON()
		jsonObject.set("bubbles", this.bubbles)
		jsonObject.set("cancelable", this.cancelable)
		jsonObject.set("x", this.x)
		jsonObject.set("y", this.y)
		jsonObject.set("clientX", this.clientX)
		jsonObject.set("clientY", this.clientY)
		jsonObject.set("pageX", this.pageX)
		jsonObject.set("pageY", this.pageY)
		jsonObject.set("screenX", this.screenX)
		jsonObject.set("screenY", this.screenY)
		return jsonObject
	}
// #endif
// #endif
}

export type UniMapControlTapEventDetail = {
	controlId : number | null;
}
export class UniMapControlTapEvent extends UniCustomEvent<UniMapControlTapEventDetail> {
	constructor(type : string, detail : UniMapControlTapEventDetail) {
		super(type, detail)
	}
}

export type UniMapAnchorPointTapEventDetail = {
	latitude : number | null;
	longitude : number | null;
}

export class UniMapAnchorPointTapEvent extends UniPointerEvent {
	detail ?: UniMapAnchorPointTapEventDetail = null
	constructor(type : string, x : number, y : number, clientX : number, clientY : number, pageX : number, pageY : number, screenX : number, screenY : number) {
		super(type, x, y, clientX, clientY, pageX, pageY, screenX, screenY)
	}
// #ifdef APP-ANDROID
// #ifndef VUE3_VAPOR
	override toJSON() : UTSJSONObject {
		const jsonObject : UTSJSONObject = super.toJSON()
		jsonObject.set("bubbles", this.bubbles)
		jsonObject.set("cancelable", this.cancelable)
		jsonObject.set("x", this.x)
		jsonObject.set("y", this.y)
		jsonObject.set("clientX", this.clientX)
		jsonObject.set("clientY", this.clientY)
		jsonObject.set("pageX", this.pageX)
		jsonObject.set("pageY", this.pageY)
		jsonObject.set("screenX", this.screenX)
		jsonObject.set("screenY", this.screenY)
		return jsonObject
	}
// #endif
// #endif
}

export type UniMapPoiTapEventDetail = {
	latitude : number | null;
	longitude : number | null;
	name : string | null;
}

export class UniMapPoiTapEvent extends UniPointerEvent {
	detail ?: UniMapPoiTapEventDetail = null
	constructor(type : string, x : number, y : number, clientX : number, clientY : number, pageX : number, pageY : number, screenX : number, screenY : number) {
		super(type, x, y, clientX, clientY, pageX, pageY, screenX, screenY)
	}
// #ifdef APP-ANDROID
// #ifndef VUE3_VAPOR
	override toJSON() : UTSJSONObject {
		const jsonObject : UTSJSONObject = super.toJSON()
		jsonObject.set("bubbles", this.bubbles)
		jsonObject.set("cancelable", this.cancelable)
		jsonObject.set("x", this.x)
		jsonObject.set("y", this.y)
		jsonObject.set("clientX", this.clientX)
		jsonObject.set("clientY", this.clientY)
		jsonObject.set("pageX", this.pageX)
		jsonObject.set("pageY", this.pageY)
		jsonObject.set("screenX", this.screenX)
		jsonObject.set("screenY", this.screenY)
		return jsonObject
	}
// #endif
// #endif
}

export type UniMapCalloutTapEventDetail = {
	markerId : number | null;
}
export class UniMapCalloutTapEvent extends UniCustomEvent<UniMapCalloutTapEventDetail> {
	constructor(type : string, detail : UniMapCalloutTapEventDetail) {
		super(type, detail)
	}
}